### ISSUE TITLE
Need to make changes to work on AWS

### ISSUE THREAD

**Issue by weihuang-jedi** [NOAA-EMC/wxflow#31]
setup_xml.py failed with messages like:

Traceback (most recent call last):
  File "/contrib/Wei.Huang/src/global-workflow-cloud/workflow/setup_xml.py", line 79, in <module>
    main()
  File "/contrib/Wei.Huang/src/global-workflow-cloud/workflow/setup_xml.py", line 73, in main
    xml = rocoto_xml_factory.create(f'{net}_{mode}', app_config, rocoto_param_dict)
  File "/contrib/Wei.Huang/src/global-workflow-cloud/workflow/wxflow/factory.py", line 71, in create
    return self._builders[key](*args, **kwargs)
  File "/contrib/Wei.Huang/src/global-workflow-cloud/workflow/rocoto/gfs_forecast_only_xml.py", line 12, in __init__
    super().__init__(app_config, rocoto_config)
  File "/contrib/Wei.Huang/src/global-workflow-cloud/workflow/rocoto/workflow_xml.py", line 28, in __init__
    task_list = get_wf_tasks(app_config)
  File "/contrib/Wei.Huang/src/global-workflow-cloud/workflow/rocoto/workflow_tasks.py", line 21, in get_wf_tasks
    tasks.append(task_obj.get_task(task_name))
  File "/contrib/Wei.Huang/src/global-workflow-cloud/workflow/rocoto/tasks.py", line 244, in get_task
    return getattr(self, task_name, *args, **kwargs)()
  File "/contrib/Wei.Huang/src/global-workflow-cloud/workflow/rocoto/gfs_tasks.py", line 29, in stage_ic
    prefix = f"{cpl_ic['BASE_CPLIC']}/{cpl_ic['CPL_ATMIC']}/@Y@m@d@H/atmos"
  File "/contrib/Wei.Huang/src/global-workflow-cloud/workflow/wxflow/attrdict.py", line 84, in __missing__
    raise KeyError(name)
KeyError: 'BASE_CPLIC'

Need to change: configuration.py to get it work on AWS.

**Comment by weihuang-jedi** [comment]
As Rahul suggested, after check the code, we figured that we can avoid the changes in wxflow.
I am closing this issue now.
Thanks,
Wei
